### ISSUE TITLE
关于%player_displayname%引用到%killer%的问题

### ISSUE THREAD

**Issue by fr1g** [Zao-chen/Diemessage#2]
关于%player_displayname%引用到%killer%的问题
仿佛不能用%killer_displayname%这种表达？
那么应该如何让信息显示killer的displayname？
（另外。对于你插件，替换受害者时候，希望使用%victim%而不是%player%以避免混淆，并为各个name提供displayname的支持，无论是玩家还是武器。我个人觉得倘若能把任何物品都能作为武器显示，将会很有趣。比如：Steve用石砖把Alex砸死了 这样的。）

**Comment by Zao-chen** [comment]
准备把%xxx%改成{xxx}，然后displayname马上会加

**Comment by Zao-chen** [comment]
1.13更新了，重命名为了{}，displayname添加了

**Comment by fr1g** [comment]
我的天 兵贵神速 star了(

**Comment by fr1g** [comment]
> 1.13更新了，重命名为了{}，displayname添加了

吔!
