### ISSUE TITLE
SpigotMC Wiki Link Error

### ISSUE THREAD

**Issue by Torben0612** [Zao-chen/Diemessage#3]
when i clicked on the wiki link in spigot mc i got a  404 not found message.

**Comment by Zao-chen** [comment]
Sorry, I haven't maintained English documents for a long time. If it weren't for you, I almost gave up English maintenance. I will update it within 24 hours. Thank you for your support.

**Comment by Torben0612** [comment]
you welcome :)

**Comment by Zao-chen** [comment]
I fix it and update the wiki.Thanks for your support.and 1.14will add the new English Languages
