### ISSUE TITLE
Suggestions丨建议

### ISSUE THREAD

**Issue by CleMooling** [Zao-chen/Diemessage#7]
The config can use the form of *.lang files, like 
{player}  drowned={player} 淹死了
And for different languages, the files can be renamed to zh_CN.lang, en_US.lang, etc.
Through this, players from different countries can receive different tips in their languages automatically. And this is pretty fun!
不装了我不是老外doge
插件的配置文件可以改成语言文件的形式，然后语句的替换可以像这样子：
{player} drowned={player} 淹死了
然后多创建几个语言文件用语言代号zh_CN、en_US等就可以实现多语言定制支持，让全世界各地的玩家进服都可以看到使用他们语言的特色死亡提示，诶嘿就很好玩
希望作者能看到并回复一下awa
插件很好，我服里面已经开始光速整活了（不是）

**Comment by CleMooling** [comment]
另外发现把{player}直接改成特定玩家名可以实现特定玩家的专属死亡提示，我觉得可以写进插件说明里面

**Comment by Zao-chen** [comment]
配置文件我是懒得改了，就用列表也蛮好的（
语音文件的话就算有了多语言，那怎么知道不同玩家用什么语音呢，要涉及到ip了（懒得搞
我准备加一个特定身份组给特定提示，就比如说vip可以金色的死亡提示（

**Comment by CleMooling** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by CleMooling** [comment]
身份组其实没什么必要，直接改变量{player}即可。
另外我是开的互通服，在IP不变的情况下把游戏设置中语言改成英文的时候互通插件提供了英文提示，所以应该有其他办法可以判定玩家所使用的语言。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月7日(周五) 上午10:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zao-chen/Diemessage] Suggestions丨建议 (Issue #7)




 
配置文件我是懒得改了，就用列表也蛮好的（
 语音文件的话就算有了多语言，那怎么知道不同玩家用什么语音呢，要涉及到ip了（懒得搞
 我准备加一个特定身份组给特定提示，就比如说vip可以金色的死亡提示（

**Comment by Zao-chen** [comment]
那你可以自己改了，我没法抓其他插件的东西，除非他有接口XD

**Comment by CleMooling** [comment]
感谢插件作者的回复，你的插件非常nice
doge
